-- automatically generated by BNF Converter
module Main where


import System.IO ( stdin, stderr, hGetContents, hPutStrLn )
import System.Environment ( getArgs, getProgName )
import System.Exit ( exitFailure, exitSuccess )
import Control.Monad (when)

import LexTurning
import ParTurning
import PrintTurning
import AbsTurning
import SemTurning
import TypeTurning



import ErrM

type ParseFun a = [Token] -> Err a

myLLexer = myLexer

type Verbosity = Int

putStrV :: Verbosity -> String -> IO ()
putStrV v s = when (v > 1) $ hPutStrLn stderr s

runFile :: Verbosity -> ParseFun Prog -> FilePath -> IO ()
runFile v p f = putStrLn f >> readFile f >>= run v p

run ::  Verbosity -> ParseFun Prog -> String -> IO ()
run v p s = let ts = myLLexer s in case p ts of
           Bad s    -> do hPutStrLn stderr "\nParse Failed...\n"
                          --putStrV v "Tokens:"
                          --putStrV v $ show ts
                          --kPutStrLn stderr s
                          exitFailure
           Ok  tree -> do --putStrLn "\nParse Successful!"
                          --showTree v tree
                          b <- checkTypes tree
                          if b
                            then do
                              interpret tree
                              exitSuccess
                            else
                              exitFailure


showTree :: (Show a, Print a) => Int -> a -> IO ()
showTree v tree
 = do
      putStrV v $ "\n[Abstract Syntax]\n\n" ++ show tree
      putStrV v $ "\n[Linearized tree]\n\n" ++ printTree tree

usage :: IO ()
usage = do
  putStrLn $ unlines
    [ "usage: Call with one of the following argument combinations:"
    , "  --help          Display this help message."
    , "  (no arguments)  Parse stdin verbosely."
    , "  (files)         Parse content of files verbosely."
    , "  -s (files)      Silent mode. Parse content of files silently."
    ]
  exitFailure

main :: IO ()
main = do
  args <- getArgs
  case args of
    ["--help"] -> usage
    [] -> getContents >>= run 2 pProg
    "-s":fs -> mapM_ (runFile 0 pProg) fs
    fs -> mapM_ (runFile 2 pProg) fs





